{-# LANGUAGE OverloadedStrings #-}
module Webhooks.Slack.Emoji
       (EMOJI(..)) where

import Data.Aeson
import Data.Text (Text)
import qualified Data.Text as T
import Control.Applicative (pure)

instance ToJSON EMOJI where
  toJSON (EIGHTBALL) = String $ toEmoji "8ball"
  toJSON x = (String . toEmoji . T.toLower . T.pack . show) x

toEmoji :: Text -> Text
toEmoji = T.append ":" . flip T.append ":"

-- | EIGHTBALL must be `:8ball:` when sent to Slack
--
-- To use a custom emoji, don't specify one and upload
-- an image to Slack
data EMOJI = GRINNING
           |GRIN
           |JOY
           |SMILEY
           |SMILE
           |SWEAT_SMILE
           |SATISFIED
           |INNOCENT
           |SMILING_IMP
           |WINK
           |BLUSH
           |YUM
           |RELIEVED
           |HEART_EYES
           |SUNGLASSES
           |SMIRK
           |NEUTRAL_FACE
           |EXPRESSIONLESS
           |UNAMUSED
           |SWEAT
           |PENSIVE
           |CONFUSED
           |CONFOUNDED
           |KISSING
           |KISSING_HEART
           |KISSING_SMILING_EYES
           |KISSING_CLOSED_EYES
           |STUCK_OUT_TONGUE
           |STUCK_OUT_TONGUE_WINKING_EYE
           |STUCK_OUT_TONGUE_CLOSED_EYES
           |DISAPPOINTED
           |WORRIED
           |ANGRY
           |RAGE
           |CRY
           |PERSEVERE
           |TRIUMPH
           |DISAPPOINTED_RELIEVED
           |FROWNING
           |ANGUISHED
           |FEARFUL
           |WEARY
           |SLEEPY
           |TIRED_FACE
           |GRIMACING
           |SOB
           |OPEN_MOUTH
           |HUSHED
           |COLD_SWEAT
           |SCREAM
           |ASTONISHED
           |FLUSHED
           |SLEEPING
           |DIZZY_FACE
           |NO_MOUTH
           |RELAXED
           |MASK
           |SMILE_CAT
           |JOY_CAT
           |SMILEY_CAT
           |HEART_EYES_CAT
           |SMIRK_CAT
           |KISSING_CAT
           |POUTING_CAT
           |CRYING_CAT_FACE
           |SCREAM_CAT
           |NO_GOOD
           |OK_WOMAN
           |BOW
           |SEE_NO_EVIL
           |HEAR_NO_EVIL
           |SPEAK_NO_EVIL
           |RAISING_HAND
           |RAISED_HANDS
           |PERSON_FROWNING
           |PERSON_WITH_POUTING_FACE
           |BUST_IN_SILHOUETTE
           |BUSTS_IN_SILHOUETTE
           |BOY
           |GIRL
           |MAN
           |WOMAN
           |FAMILY
           |COUPLE
           |TWO_MEN_HOLDING_HANDS
           |TWO_WOMEN_HOLDING_HANDS
           |COP
           |DANCERS
           |BRIDE_WITH_VEIL
           |PERSON_WITH_BLOND_HAIR
           |MAN_WITH_GUA_PI_MAO
           |MAN_WITH_TURBAN
           |OLDER_MAN
           |OLDER_WOMAN
           |BABY
           |CONSTRUCTION_WORKER
           |PRINCESS
           |JAPANESE_OGRE
           |JAPANESE_GOBLIN
           |GHOST
           |ANGEL
           |ALIEN
           |SPACE_INVADER
           |IMP
           |SKULL
           |INFORMATION_DESK_PERSON
           |GUARDSMAN
           |RAT
           |MOUSE2
           |OX
           |WATER_BUFFALO
           |COW2
           |TIGER2
           |LEOPARD
           |RABBIT2
           |CAT2
           |DRAGON
           |CROCODILE
           |WHALE2
           |SNAIL
           |SNAKE
           |RACEHORSE
           |RAM
           |GOAT
           |SHEEP
           |MONKEY
           |ROOSTER
           |CHICKEN
           |DOG2
           |PIG2
           |BOAR
           |ELEPHANT
           |OCTOPUS
           |SHELL
           |BUG
           |ANT
           |HONEYBEE
           |BEETLE
           |FISH
           |TROPICAL_FISH
           |BLOWFISH
           |TURTLE
           |HATCHING_CHICK
           |BABY_CHICK
           |HATCHED_CHICK
           |BIRD
           |PENGUIN
           |KOALA
           |POODLE
           |DROMEDARY_CAMEL
           |CAMEL
           |FLIPPER
           |MOUSE
           |COW
           |TIGER
           |RABBIT
           |CAT
           |DRAGON_FACE
           |WHALE
           |HORSE
           |MONKEY_FACE
           |DOG
           |PIG
           |FROG
           |HAMSTER
           |WOLF
           |BEAR
           |PANDA_FACE
           |PIG_NOSE
           |PAW_PRINTS
           |EYES
           |EAR
           |NOSE
           |LIPS
           |TONGUE
           |POINT_UP
           |FIST
           |RAISED_HAND
           |V
           |POINT_UP_2
           |POINT_DOWN
           |POINT_LEFT
           |POINT_RIGHT
           |PUNCH
           |WAVE
           |OK_HAND
           |THUMBSUP
           |THUMBSDOWN
           |CLAP
           |OPEN_HANDS
           |HAMBURGER
           |PIZZA
           |MEAT_ON_BONE
           |POULTRY_LEG
           |RICE_CRACKER
           |RICE_BALL
           |RICE
           |CURRY
           |RAMEN
           |SPAGHETTI
           |BREAD
           |FRIES
           |SWEET_POTATO
           |DANGO
           |ODEN
           |SUSHI
           |FRIED_SHRIMP
           |FISH_CAKE
           |ICECREAM
           |SHAVED_ICE
           |ICE_CREAM
           |DOUGHNUT
           |COOKIE
           |CHOCOLATE_BAR
           |CANDY
           |LOLLIPOP
           |CUSTARD
           |HONEY_POT
           |CAKE
           |BENTO
           |STEW
           |EGG
           |FORK_AND_KNIFE
           |TEA
           |SAKE
           |WINE_GLASS
           |COCKTAIL
           |TROPICAL_DRINK
           |BEER
           |BEERS
           |BABY_BOTTLE
           |MUSHROOM
           |TOMATO
           |EGGPLANT
           |GRAPES
           |MELON
           |WATERMELON
           |TANGERINE
           |LEMON
           |BANANA
           |PINEAPPLE
           |APPLE
           |GREEN_APPLE
           |PEAR
           |PEACH
           |CHERRIES
           |STRAWBERRY
           |CHESTNUT
           |SEEDLING
           |EVERGREEN_TREE
           |DECIDUOUS_TREE
           |PALM_TREE
           |CACTUS
           |TULIP
           |CHERRY_BLOSSOM
           |ROSE
           |HIBISCUS
           |SUNFLOWER
           |BLOSSOM
           |CORN
           |EAR_OF_RICE
           |HERB
           |FOUR_LEAF_CLOVER
           |MAPLE_LEAF
           |FALLEN_LEAF
           |LEAVES
           |SUNNY
           |CLOUD
           |TELEPHONE
           |UMBRELLA
           |COFFEE
           |SPADES
           |CLUBS
           |HEARTS
           |DIAMONDS
           |RECYCLE
           |WHEELCHAIR
           |WARNING
           |COPYRIGHT
           |REGISTERED
           |TM
           |ZAP
           |SOCCER
           |BASEBALL
           |SNOWMAN
           |PARTLY_SUNNY
           |NO_ENTRY
           |GOLF
           |SAILBOAT
           |FUELPUMP
           |SCISSORS
           |BALLOT_BOX_WITH_CHECK
           |WHITE_CHECK_MARK
           |AIRPLANE
           |ENVELOPE
           |PENCIL2
           |BLACK_NIB
           |HEAVY_CHECK_MARK
           |HEAVY_MULTIPLICATION_X
           |SPARKLES
           |SNOWFLAKE
           |X
           |NEGATIVE_SQUARED_CROSS_MARK
           |QUESTION
           |HEAVY_EXCLAMATION_MARK
           |BANGBANG
           |INTERROBANG
           |HEART
           |HEAVY_PLUS_SIGN
           |HEAVY_MINUS_SIGN
           |HEAVY_DIVISION_SIGN
           |STAR
           |O
           |BLACK_JOKER
           |CYCLONE
           |FOGGY
           |CLOSED_UMBRELLA
           |SUNRISE
           |OCEAN
           |EARTH_AFRICA
           |EARTH_AMERICAS
           |EARTH_ASIA
           |GLOBE_WITH_MERIDIANS
           |WAXING_CRESCENT_MOON
           |WANING_GIBBOUS_MOON
           |LAST_QUARTER_MOON
           |WANING_CRESCENT_MOON
           |CRESCENT_MOON
           |NEW_MOON_WITH_FACE
           |FIRST_QUARTER_MOON_WITH_FACE
           |LAST_QUARTER_MOON_WITH_FACE
           |FULL_MOON_WITH_FACE
           |SUN_WITH_FACE
           |STAR2
           |RIBBON
           |GIFT
           |BIRTHDAY
           |JACK_O_LANTERN
           |CHRISTMAS_TREE
           |SANTA
           |FIREWORKS
           |SPARKLER
           |BALLOON
           |TADA
           |CONFETTI_BALL
           |TANABATA_TREE
           |CROSSED_FLAGS
           |BAMBOO
           |DOLLS
           |FLAGS
           |WIND_CHIME
           |RICE_SCENE
           |SCHOOL_SATCHEL
           |MORTAR_BOARD
           |MICROPHONE
           |MOVIE_CAMERA
           |CINEMA
           |HEADPHONES
           |ART
           |TOPHAT
           |CIRCUS_TENT
           |TICKET
           |CLAPPER
           |PERFORMING_ARTS
           |VIDEO_GAME
           |DART
           |SLOT_MACHINE
           |EIGHTBALL
           |GAME_DIE
           |BOWLING
           |FLOWER_PLAYING_CARDS
           |MUSICAL_NOTE
           |NOTES
           |SAXOPHONE
           |GUITAR
           |MUSICAL_KEYBOARD
           |TRUMPET
           |VIOLIN
           |MUSICAL_SCORE
           |TENNIS
           |SKI
           |BASKETBALL
           |CHECKERED_FLAG
           |SNOWBOARDER
           |RUNNING
           |SURFER
           |TROPHY
           |HORSE_RACING
           |FOOTBALL
           |RUGBY_FOOTBALL
           |SWIMMER
           |DANCER
           |LIPSTICK
           |NAIL_CARE
           |MASSAGE
           |HAIRCUT
           |BARBER
           |SYRINGE
           |PILL
           |KISS
           |LOVE_LETTER
           |RING
           |GEM
           |COUPLEKISS
           |BOUQUET
           |COUPLE_WITH_HEART
           |WEDDING
           |HEARTBEAT
           |BROKEN_HEART
           |TWO_HEARTS
           |SPARKLING_HEART
           |HEARTPULSE
           |CUPID
           |BLUE_HEART
           |GREEN_HEART
           |YELLOW_HEART
           |PURPLE_HEART
           |GIFT_HEART
           |REVOLVING_HEARTS
           |HEART_DECORATION
           |DIAMOND_SHAPE_WITH_A_DOT_INSIDE
           |BULB
           |ANGER
           |BOMB
           |ZZZ
           |COLLISION
           |SWEAT_DROPS
           |DROPLET
           |DASH
           |SHIT
           |MUSCLE
           |DIZZY
           |SPEECH_BALLOON
           |THOUGHT_BALLOON
           |HEAVY_DOLLAR_SIGN
           |CREDIT_CARD
           |YEN
           |DOLLAR
           |EURO
           |POUND
           |MONEY_WITH_WINGS
           |SEAT
           |COMPUTER
           |BRIEFCASE
           |MINIDISC
           |FLOPPY_DISK
           |CD
           |DVD
           |FILE_FOLDER
           |OPEN_FILE_FOLDER
           |PAGE_WITH_CURL
           |PAGE_FACING_UP
           |DATE
           |CARD_INDEX
           |CHART_WITH_UPWARDS_TREND
           |CHART_WITH_DOWNWARDS_TREND
           |BAR_CHART
           |PUSHPIN
           |ROUND_PUSHPIN
           |PAPERCLIP
           |NOTEBOOK
           |OPEN_BOOK
           |BOOKS
           |PENCIL
           |TELEPHONE_RECEIVER
           |PAGER
           |FAX
           |SATELLITE
           |LOUDSPEAKER
           |MEGA
           |OUTBOX_TRAY
           |INBOX_TRAY
           |PACKAGE
           |MAILBOX_CLOSED
           |MAILBOX
           |MAILBOX_WITH_MAIL
           |MAILBOX_WITH_NO_MAIL
           |POSTBOX
           |POSTAL_HORN
           |NEWSPAPER
           |IPHONE
           |NO_MOBILE_PHONES
           |CAMERA
           |VIDEO_CAMERA
           |TV
           |RADIO
           |VHS
           |LOW_BRIGHTNESS
           |HIGH_BRIGHTNESS
           |MUTE
           |SOUND
           |SPEAKER
           |BATTERY
           |ELECTRIC_PLUG
           |MAG
           |MAG_RIGHT
           |LOCK_WITH_INK_PEN
           |CLOSED_LOCK_WITH_KEY
           |KEY
           |LOCK
           |UNLOCK
           |BELL
           |NO_BELL
           |BOOKMARK
           |LINK
           |RADIO_BUTTON
           |UNDERAGE
           |FIRE
           |FLASHLIGHT
           |WRENCH
           |HAMMER
           |NUT_AND_BOLT
           |HOCHO
           |GUN
           |MICROSCOPE
           |TELESCOPE
           |CRYSTAL_BALL
           |CLOCK3
           |PRAY
           |ROCKET
           |HELICOPTER
           |STEAM_LOCOMOTIVE
           |TRAIN
           |BULLETTRAIN_SIDE
           |BULLETTRAIN_FRONT
           |TRAIN2
           |LIGHT_RAIL
           |STATION
           |TRAM
           |BUS
           |ONCOMING_BUS
           |TROLLEYBUS
           |BUSSTOP
           |MINIBUS
           |AMBULANCE
           |FIRE_ENGINE
           |POLICE_CAR
           |ONCOMING_POLICE_CAR
           |TAXI
           |ONCOMING_TAXI
           |RED_CAR
           |ONCOMING_AUTOMOBILE
           |BLUE_CAR
           |TRUCK
           |ARTICULATED_LORRY
           |TRACTOR
           |MONORAIL
           |MOUNTAIN_RAILWAY
           |SUSPENSION_RAILWAY
           |MOUNTAIN_CABLEWAY
           |AERIAL_TRAMWAY
           |SHIP
           |ROWBOAT
           |SPEEDBOAT
           |TRAFFIC_LIGHT
           |VERTICAL_TRAFFIC_LIGHT
           |CONSTRUCTION
           |ROTATING_LIGHT
           |TRIANGULAR_FLAG_ON_POST
           |DOOR
           |HOUSE
           |HOUSE_WITH_GARDEN
           |EUROPEAN_POST_OFFICE
           |CONVENIENCE_STORE
           |SCHOOL
           |NO_ENTRY_SIGN
           |SMOKING
           |NO_SMOKING
           |PUT_LITTER_IN_ITS_PLACE
           |BIKE
           |NO_BICYCLES
           |BICYCLIST
           |MOUNTAIN_BICYCLIST
           |WALKING
           |NO_PEDESTRIANS
           |MENS
           |WOMENS
           |TOILET
           |SHOWER
           |BATH
           |BATHTUB
           |CN
           |DE
           |ES
           |FR
           |UK
           |IT
           |JP
           |KR
           |RU
           |US deriving Show

